image: node:10.9

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@8.3.21
  - npm install
  - ng build
  - mv dist/dotaInfo/* public/
  artifacts:
    paths:
    - public
  only:
  - master
  - pages